version: 0.2
        
phases:
  install:
    runtime-versions:
      java: openjdk8
    commands:
      - echo install

  pre_build:
    commands:
      - echo post build
      - command
  build:
    commands:
      - mvn package
      - echo build

  post_build:
    commands:
      - echo post build
artifacts:
  files:
    - target\spring-boot-hello-world-rest-api-0.0.1-SNAPSHOT.jar
